spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.121/springcloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:          # 配置rabbitMQ
    host: 192.168.2.121
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.81:8761/eureka/,http://192.168.2.81:8761/eureka/
server:
  port: 8080

girl:
  name: product
  age: 201
