spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://192.168.2.121:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  rabbitmq:          # 配置rabbitMQ
    host: 192.168.2.121
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.81:8761/eureka/,http://192.168.2.81:8761/eureka/
server:
  port: 8080

girl:
  name: product
  age: 201

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
